In [1]:
import numpy as np
import torch
import torch.nn as nn

from lamp import *

In [2]:
## CREATING DATASET

datax = [
    [[0.1517, 0.5443, 0.1664, 0.2968, 0.1047, 0.2303, 0.7809, 0.8742]],
    [[0.6482, 0.8415, 0.3437, 0.5621, 0.8318, 0.5978, 0.2179, 0.5826]],
    [[0.0959, 0.5683, 0.8281, 0.2220, 0.7972, 0.3602, 0.9269, 0.3220]],
    [[0.2017, 0.4027, 0.9019, 0.3093, 0.2855, 0.0226, 0.3115, 0.5141]],
]

# data shape
batch, chan_in, length = np.array(datax).shape

# conv shape
k_size = 3
chan_out = 2

params = np.random.rand(k_size, chan_in, chan_out)
np_input = np.array(datax).reshape(batch, length, chan_in)
th_input = torch.Tensor(datax)

## Conv1D

In [3]:
## CONV1D FORWARD

conv = Conv1D(k_size, chan_in, chan_out)
output = conv.forward(np_input)
np.round_(output.reshape(batch, chan_out, -1), decimals=4)

array([[[ 0.0223, -0.0459,  0.0511, -0.0631,  0.0178, -0.0327],
        [ 0.0324, -0.0366,  0.0578, -0.0378,  0.0739, -0.0802]],

       [[ 0.0636, -0.1092,  0.0861, -0.1043,  0.0765, -0.0777],
        [ 0.0752, -0.1064,  0.0646, -0.1098,  0.0729, -0.0765]],

       [[ 0.0622, -0.056 ,  0.0511, -0.0989,  0.1   , -0.1016],
        [ 0.0402, -0.0696,  0.1074, -0.1089,  0.0463, -0.0879]],

       [[ 0.0721, -0.0581,  0.0477, -0.0901,  0.0715, -0.102 ],
        [ 0.0206, -0.043 ,  0.0366, -0.0329,  0.0363, -0.0293]]])

In [4]:
conv_ = nn.Conv1d(chan_in, chan_out, k_size)
output = conv_(th_input)
output

tensor([[[-0.1382, -0.1606, -0.0805, -0.0533,  0.0845, -0.1160],
         [-0.3873, -0.5314, -0.4382, -0.5168, -0.5685, -0.4591]],

        [[-0.3980, -0.2876, -0.1035, -0.3150, -0.4213, -0.1471],
         [-0.3818, -0.5562, -0.5136, -0.4224, -0.4329, -0.5728]],

        [[-0.0055, -0.3831, -0.2038, -0.2087, -0.2099, -0.3106],
         [-0.4933, -0.3579, -0.6262, -0.3644, -0.6128, -0.3360]],

        [[ 0.0146, -0.3226, -0.3508, -0.1497, -0.0095,  0.0460],
         [-0.5546, -0.3430, -0.5205, -0.4370, -0.5504, -0.4959]]],
       grad_fn=<SqueezeBackward1>)

## MaxPool1D

In [5]:
maxp = MaxPool1D(k_size, stride=1)
output = maxp.forward(np_input)
np.round_(output.reshape(batch, chan_in, -1), decimals=4)
# print(maxp.indx)

# maxp.backward_delta(np_input, output)


array([[[0.5443, 0.1517, 0.5443, 0.1517, 0.1664, 0.1664]],

       [[0.8415, 0.6482, 0.8415, 0.6482, 0.3437, 0.3437]],

       [[0.5683, 0.0959, 0.5683, 0.0959, 0.8281, 0.8281]],

       [[0.4027, 0.2017, 0.4027, 0.2017, 0.9019, 0.9019]]])

In [25]:
stride = 1
d_out = (length - k_size) // stride + 1
res = np.zeros((batch, d_out, chan_in))

indx = []
compte = 0
for k in range(d_out):
    t1, t2 = stride * k, 2 * (k_size // 2) + k * stride + 1
    tupleA = np.argmax(np_input[:, t1:t2, :], axis=1)

    compte += tupleA[0].item()
    # renvois pas 1 mais indice a corriger
    # listProv = [0] * (tupleA[0][0].item()-1) + tupleA[0].tolist()

    indx += [compte]
    res[:, k, :] = np_input[:, tupleA, :].squeeze(axis=1)

# np.array(indx)
np.round_(res.reshape(batch, chan_in, -1), decimals=4)

[[1 1 2 2]]


ValueError: cannot select an axis to squeeze out which has size not equal to one

In [6]:
maxp_ = nn.MaxPool1d(k_size, stride=1)
output = maxp_(th_input)
output

tensor([[[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742]],

        [[0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978]],

        [[0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269]],

        [[0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]]])

In [7]:
stride = 3
d_out = (length - k_size) // stride + 1
res = np.zeros((batch, d_out, chan_in))

for k in range(d_out):
    t1, t2 = stride * k, 2 * (k_size // 2) + k * stride + 1
    res[:, k, :] = np.amax(np_input[:, t1:t2, :], axis=1)

res.reshape(batch, chan_in, -1)

array([[[0.5443, 0.2968]],

       [[0.8415, 0.8318]],

       [[0.8281, 0.7972]],

       [[0.9019, 0.3093]]])

In [8]:
res = np.zeros((batch, d_out, chan_in))
print(np_input)

for k in range(d_out):
    t1, t2 = stride * k, 2 * (k_size // 2) + k * stride + 1
    amax = np.amax(np_input[:, t1:t2, :], axis=1).flatten()
    # print(amax)
    # print(np.where(np_input == amax, 1, 0))
    idx = np.where(np.all(np_input == amax, axis=-1))[0]
    print(idx)
    # res[:, k, :] = np_input[:, idx:]

# res.reshape(batch, chan_in, -1)

[[[0.1517]
  [0.5443]
  [0.1664]
  [0.2968]
  [0.1047]
  [0.2303]
  [0.7809]
  [0.8742]]

 [[0.6482]
  [0.8415]
  [0.3437]
  [0.5621]
  [0.8318]
  [0.5978]
  [0.2179]
  [0.5826]]

 [[0.0959]
  [0.5683]
  [0.8281]
  [0.222 ]
  [0.7972]
  [0.3602]
  [0.9269]
  [0.322 ]]

 [[0.2017]
  [0.4027]
  [0.9019]
  [0.3093]
  [0.2855]
  [0.0226]
  [0.3115]
  [0.5141]]]
[]
[]


In [9]:
input = maxp.forward(np_input)

m5 = Flatten()
output = m5.forward(input)
output

array([[0.5443, 0.1517, 0.5443, 0.1517, 0.1664, 0.1664],
       [0.8415, 0.6482, 0.8415, 0.6482, 0.3437, 0.3437],
       [0.5683, 0.0959, 0.5683, 0.0959, 0.8281, 0.8281],
       [0.4027, 0.2017, 0.4027, 0.2017, 0.9019, 0.9019]])

In [10]:
input = maxp_(th_input)

m6 = nn.Flatten()
output = m6(input)
output

tensor([[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742],
        [0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978],
        [0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269],
        [0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]])

In [11]:
a = np.ones((4, 3, 2))
print(a)
a = np.insert(a,[0],0 ,axis= 1)

print(a)
print(a.shape)

for i in range(0, 8):
    if i%2 != 0 :   
        a = np.insert(a,i,0 ,axis= 1)
print(a.shape)        


[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[0. 0.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[0. 0.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[0. 0.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
(4, 4, 2)
(4, 8, 2)


In [12]:
a = np.arange(10)

a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#update gradient conv
stride = 2
m1 = Conv1D(k_size, chan_in, chan_out, stride=stride)
delta = m1.forward(np_input)

d_out = (length - k_size) // stride + 1
print(d_out)
res = np.zeros((k_size, chan_in, chan_out))

for k in range(k_size):
    print(k)
    t1, t2 = k * stride, d_out + k * stride 
    print(t1, t2)
    print(np_input[:, t1:t2, :, np.newaxis])
    res[k,: , :] = np.sum(
            np_input[:, t1:t2, :, np.newaxis]
            * delta[:, :,np.newaxis ,:],
            axis=(0,1),
        )


3
0
0 3
[[[[0.1517]]

  [[0.5443]]

  [[0.1664]]]


 [[[0.6482]]

  [[0.8415]]

  [[0.3437]]]


 [[[0.0959]]

  [[0.5683]]

  [[0.8281]]]


 [[[0.2017]]

  [[0.4027]]

  [[0.9019]]]]
1
2 5
[[[[0.1664]]

  [[0.2968]]

  [[0.1047]]]


 [[[0.3437]]

  [[0.5621]]

  [[0.8318]]]


 [[[0.8281]]

  [[0.222 ]]

  [[0.7972]]]


 [[[0.9019]]

  [[0.3093]]

  [[0.2855]]]]
2
4 7
[[[[0.1047]]

  [[0.2303]]

  [[0.7809]]]


 [[[0.8318]]

  [[0.5978]]

  [[0.2179]]]


 [[[0.7972]]

  [[0.3602]]

  [[0.9269]]]


 [[[0.2855]]

  [[0.0226]]

  [[0.3115]]]]


In [14]:
stride = 2
m1 = Conv1D(k_size, chan_in, chan_out, stride=stride)
delta = m1.forward(np_input)

print(delta.shape)
d_out = length

res = np.zeros((batch, length, chan_in))

if stride > 1:
    for i in range(0, m1.sizeOut + 1):
        if i % stride == 1:
            continue
        delta = np.insert(delta, i, 0, axis=1)

print(delta.shape)
for kd, kr in enumerate(list(range(0, d_out, stride))):
    print("kd", kd, " kr", kr)
    t1, t2 = 0, k_size
    d1 = -kd - 2 + k_size
    d2 = -kd - 2

    if kd == 0:
        t1, t2 = 0, kd + 1
        d1, d2 = None, -1

    elif kd < k_size - 1:
        print("1")
        t1, t2 = 0, kd + 1
        d1, d2 = -1, -kd - 2

    elif kd > d_out - (k_size + 1):
        print("2")
        t1, t2 = k_size - d_out + kd, k_size
        d1, d2 = -kd + 2, 0

    print(d1, d2, kr, kd)
    print(np.flip(params, axis=1)[np.newaxis, t1:t2, :, :])
    print(delta[:, d2:d1, np.newaxis, :])

    res[:, kr, :] = np.sum(
        np.flip(params, axis=1)[np.newaxis, t1:t2, :, :]
        * delta[:, d2:d1, np.newaxis, :],
        axis=(1, 3),
    )

res.shape, np_input.shape


(4, 3, 2)


AttributeError: 'Conv1D' object has no attribute 'sizeOut'

In [ ]:




x, y, z = np.ogrid[:2,:4,:5]
M = 100*x + 10*y + z
M.shape
(2, 4, 5)
print(M)
inds = [(0, 0), (2, 1), (3, 4), (1, 2)]
inds_array = np.moveaxis(np.array(inds), -1, 0); inds_array

M[np.index_exp[:] + tuple([1])]  # same as M[:, [0, 2, 3, 1], [0, 1, 4, 2]]

M[:, [0, 2, 3, 1], [0, 1, 4, 2]]


[[[  0   1   2   3   4]
  [ 10  11  12  13  14]
  [ 20  21  22  23  24]
  [ 30  31  32  33  34]]

 [[100 101 102 103 104]
  [110 111 112 113 114]
  [120 121 122 123 124]
  [130 131 132 133 134]]]


array([[  0,  21,  34,  12],
       [100, 121, 134, 112]])

In [ ]:
p = [1,0,2,5]

p += [2]



t = [0 ]* 4 + [1]
t

[0, 0, 0, 0, 1]