In [2]:
import numpy as np
import torch
import torch.nn as nn

In [82]:
datax = [
    [[0.1517, 0.5443, 0.1664, 0.2968, 0.1047, 0.2303, 0.7809, 0.8742]],
    [[0.6482, 0.8415, 0.3437, 0.5621, 0.8318, 0.5978, 0.2179, 0.5826]],
    [[0.0959, 0.5683, 0.8281, 0.2220, 0.7972, 0.3602, 0.9269, 0.3220]],
    [[0.2017, 0.4027, 0.9019, 0.3093, 0.2855, 0.0226, 0.3115, 0.5141]],
]


# data shape
batch = 4
length = 8

# conv shape
k_size = 3
chan_in = 1
chan_out = 2

params = np.random.rand(k_size, chan_in, chan_out)


AttributeError: 'list' object has no attribute 'size'

In [83]:
np_input = np.array(datax).reshape(batch, length, chan_in)
print(np_input.shape)
th_input = torch.Tensor(datax)

(4, 8, 1)


In [80]:
from lamp.conv import Conv1D

m1 = Conv1D(k_size, chan_in, chan_out)
output = m1.forward(np_input)
print(output.shape)
np.round_(output.reshape(batch, chan_out, -1), decimals=4)

(4, 6, 2)


array([[[ 0.0463,  0.0321,  0.0064, -0.0147,  0.023 ,  0.0132],
        [ 0.0071, -0.0065,  0.0442,  0.0174,  0.0893,  0.0508]],

       [[ 0.0609,  0.0283,  0.0208, -0.0157,  0.0657,  0.0287],
        [ 0.0722,  0.0344,  0.0298,  0.    ,  0.0193, -0.0115]],

       [[ 0.0744,  0.0424,  0.058 ,  0.0306,  0.0198, -0.0217],
        [ 0.0721,  0.0481,  0.0371, -0.0091,  0.0769,  0.0496]],

       [[ 0.0597,  0.0255,  0.0729,  0.0455,  0.0058, -0.0238],
        [ 0.0142,  0.004 ,  0.0037, -0.011 ,  0.044 ,  0.0254]]])

In [78]:
m2 = nn.Conv1d(chan_in, chan_out, k_size)
output = m2(th_input)
output.shape

torch.Size([4, 2, 6])

In [7]:
from lamp import MaxPool1D

m3 = MaxPool1D(k_size, stride=1)
output = m3.forward(np_input)
output.reshape(batch, chan_in, -1)

array([[[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742]],

       [[0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978]],

       [[0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269]],

       [[0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]]])

In [42]:
m4 = nn.MaxPool1d(k_size, stride=1)
output = m4(th_input)
output

tensor([[[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742]],

        [[0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978]],

        [[0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269]],

        [[0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]]])

In [9]:
input = m4(th_input)
# With default parameters
m6 = nn.Flatten()
output = m6(input)
output.size(), output

(torch.Size([4, 6]),
 tensor([[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742],
         [0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978],
         [0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269],
         [0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]]))

In [10]:
from lamp import Flatten

input = m3.forward(np_input)

m5 = Flatten()
output = m5.forward(input)
output.shape, output

((4, 6),
 array([[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742],
        [0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978],
        [0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269],
        [0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]]))

In [14]:
stride = 1
from lamp.conv import Conv1D

m1 = Conv1D(k_size, chan_in, chan_out)
output = m1.forward(np_input)
np.round_(output.reshape(batch, chan_out, -1), decimals=4)

from lamp import MaxPool1D

m3 = MaxPool1D(k_size, stride=1)
output2 = m3.forward(np_input)
output2.reshape(batch, chan_in, -1)


array([[[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742]],

       [[0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978]],

       [[0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269]],

       [[0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]]])

In [ ]:
for k in range(d_out):
            t1, t2 = k * self.stride, 2 * (self.k_size // 2) + k * self.stride + 1
            res[:, k, :] = np.sum(
                X[:, t1:t2, :, np.newaxis] * self._parameters[np.newaxis, :, :, :],
                axis=(1, 2),
            )


 for i in range(d_out):
            out[:,i, :] = np.sum(X[:,self.k_size//2+i*self.stride -self.k_size//2:self.k_size//2+i*self.stride +self.k_size//2+1, :, np.newaxis] * self._parameters[np.newaxis, :, :, : ],axis = (1,2))

In [162]:
li = np.arange(10)
print(li)
print(li[-3:-1])

[0 1 2 3 4 5 6 7 8 9]
[7 8]


In [165]:
m1 = Conv1D(k_size, chan_in, chan_out)
output = m1.forward(np_input)

delta = output
print(output, k_size)
d_out = (length - k_size) // stride + 1

d_out = 8
res = np.zeros((batch, d_out, chan_in))
for k in range(d_out):
    t1, t2 = 0, k_size 
    print("k", k, k_size)

    d1 = - k * stride - 2 + k_size
    d2 = - (k * stride + 2)
    print(t1,t2)    
    print(d2,d1)
    if k == 0 :
        print ("k == 0")
        t1 = 0
        t2 = k + 1
        d1 = None
        d2 = - 1
    elif k <= k_size -1 :
        print ("k < k_size")
        t1 = 0
        t2 = k + 1
        d1 = - 1
        d2 = - k -2
    elif k > d_out - k_size :
        print ("k > d_out - k_size")
        t1 = k
        t2 = d_out
        d2 = k_size - (d_out - k ) 
   
    print(t1,t2)    
    print(d2,d1)
    ari = np.flip(params, axis=1)[ np.newaxis, t1:t2, :,  :]
    
    print("delta",delta[  :, d2:d1, np.newaxis, :])
    print("ari",ari)
    res[:, k, :] = np.sum(
        np.flip(params, axis=1)[ np.newaxis, t1:t2, :,  :]
        * delta[  :, d2:d1, np.newaxis, :],
        axis=(1,3)
    )
    print(res[:, k, :])
    print(delta)
print(res.shape)
print(res)

[[[-6.87258451e-02 -2.11219888e-02]
  [-7.79098846e-02 -2.55767256e-03]
  [-4.48583650e-02 -1.32038921e-02]
  [-4.90667197e-02  3.69008790e-03]
  [-8.86969193e-02  5.04643203e-02]
  [-1.50155829e-01  2.36370797e-02]]

 [[-1.44135916e-01 -3.95015975e-02]
  [-1.35676830e-01  9.37615742e-05]
  [-1.37547527e-01  2.82191645e-02]
  [-1.57133519e-01 -1.42568799e-02]
  [-1.28128903e-01 -4.30943743e-02]
  [-1.08852751e-01  1.72043403e-02]]

 [[-1.19185206e-01  3.60914254e-02]
  [-1.27370501e-01 -4.64223095e-02]
  [-1.43533837e-01  2.74108271e-02]
  [-1.09920907e-01 -2.09621048e-02]
  [-1.62745841e-01  3.19210529e-02]
  [-1.27745284e-01 -3.61706582e-02]]

 [[-1.19572165e-01  4.79326699e-02]
  [-1.27893021e-01 -3.73365008e-02]
  [-1.15387913e-01 -2.37495890e-02]
  [-4.81133372e-02 -2.45237119e-02]
  [-4.80337395e-02  1.55731669e-02]
  [-6.78768554e-02  2.59653854e-02]]] 3
k 0 3
0 3
-2 1
k == 0
0 1
-1 None
delta [[[[-0.15015583  0.02363708]]]


 [[[-0.10885275  0.01720434]]]


 [[[-0.12774528 -0.0

ValueError: operands could not be broadcast together with shapes (1,3,1,2) (4,2,1,2) 