In [2]:
import numpy as np
import torch
import torch.nn as nn

In [3]:
datax = [
    [[0.1517, 0.5443, 0.1664, 0.2968, 0.1047, 0.2303, 0.7809, 0.8742]],
    [[0.6482, 0.8415, 0.3437, 0.5621, 0.8318, 0.5978, 0.2179, 0.5826]],
    [[0.0959, 0.5683, 0.8281, 0.2220, 0.7972, 0.3602, 0.9269, 0.3220]],
    [[0.2017, 0.4027, 0.9019, 0.3093, 0.2855, 0.0226, 0.3115, 0.5141]],
]


# data shape
batch = 4
length = 8

# conv shape
k_size = 3
chan_in = 1
chan_out = 2

params = np.random.rand(k_size, chan_in, chan_out)


In [4]:
np_input = np.array(datax).reshape(batch, length, chan_in)
print(np_input.shape)
th_input = torch.Tensor(datax)

(4, 8, 1)


In [5]:
from lamp.conv import Conv1D

m1 = Conv1D(k_size, chan_in, chan_out)
output = m1.forward(np_input)
print(output.shape)
np.round_(output.reshape(batch, chan_out, -1), decimals=4)

(4, 6, 2)


array([[[-0.046 , -0.0106, -0.0249,  0.0589, -0.0257,  0.0029],
        [-0.0177,  0.0357, -0.0517,  0.0454, -0.0949,  0.0271]],

       [[-0.0747,  0.0275, -0.0493,  0.0921, -0.0774,  0.0492],
        [-0.0857,  0.0367, -0.0516,  0.0523, -0.0415,  0.0791]],

       [[-0.0778,  0.0256, -0.0683,  0.0131, -0.0514,  0.1141],
        [-0.0727, -0.008 , -0.0671,  0.1106, -0.08  , -0.0062]],

       [[-0.0694,  0.051 , -0.0776, -0.0014, -0.0342,  0.082 ],
        [-0.021 ,  0.0115, -0.0156,  0.0452, -0.0454,  0.0151]]])

In [6]:
m2 = nn.Conv1d(chan_in, chan_out, k_size)
output = m2(th_input)
output.shape

torch.Size([4, 2, 6])

In [7]:
from lamp import MaxPool1D

m3 = MaxPool1D(k_size, stride=1)
output = m3.forward(np_input)
output.reshape(batch, chan_in, -1)

array([[[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742]],

       [[0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978]],

       [[0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269]],

       [[0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]]])

In [8]:
m4 = nn.MaxPool1d(k_size, stride=1)
output = m4(th_input)
output

tensor([[[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742]],

        [[0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978]],

        [[0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269]],

        [[0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]]])

In [9]:
input = m4(th_input)
# With default parameters
m6 = nn.Flatten()
output = m6(input)
output.size(), output

(torch.Size([4, 6]),
 tensor([[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742],
         [0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978],
         [0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269],
         [0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]]))

In [10]:
from lamp import Flatten

input = m3.forward(np_input)

m5 = Flatten()
output = m5.forward(input)
output.shape, output

((4, 6),
 array([[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742],
        [0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978],
        [0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269],
        [0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]]))

In [11]:
stride = 1
from lamp.conv import Conv1D

m1 = Conv1D(k_size, chan_in, chan_out)
output = m1.forward(np_input)
np.round_(output.reshape(batch, chan_out, -1), decimals=4)

from lamp import MaxPool1D

m3 = MaxPool1D(k_size, stride=1)
output2 = m3.forward(np_input)
output2.reshape(batch, chan_in, -1)


array([[[0.5443, 0.5443, 0.2968, 0.2968, 0.7809, 0.8742]],

       [[0.8415, 0.8415, 0.8318, 0.8318, 0.8318, 0.5978]],

       [[0.8281, 0.8281, 0.8281, 0.7972, 0.9269, 0.9269]],

       [[0.9019, 0.9019, 0.9019, 0.3093, 0.3115, 0.5141]]])

In [13]:
for k in range(d_out):
            t1, t2 = k * self.stride, 2 * (self.k_size // 2) + k * self.stride + 1
            res[:, k, :] = np.sum(
                X[:, t1:t2, :, np.newaxis] * self._parameters[np.newaxis, :, :, :],
                axis=(1, 2),
            )


 for i in range(d_out):
            out[:,i, :] = np.sum(X[:,self.k_size//2+i*self.stride -self.k_size//2:self.k_size//2+i*self.stride +self.k_size//2+1, :, np.newaxis] * self._parameters[np.newaxis, :, :, : ],axis = (1,2))

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

In [ ]:
li = np.arange(8)
print(li)
print(li[0:-7])

[0 1 2 3 4 5 6 7]
[0]


In [17]:
m1 = Conv1D(k_size, chan_in, chan_out)
output = m1.forward(np_input)

delta = output
print(output, k_size)
d_out = (length - k_size) // stride + 1

d_out = 8
res = np.zeros((batch, d_out, chan_in))
for k in range(d_out):
    t1, t2 = 0, k_size 
    d1 = - k * stride - 2 + k_size
    d2 = - (k * stride + 2)
  
    if k == 0 :
       
        t1 = 0
        t2 = k + 1
        d1 = None
        d2 = - 1
    elif k <= k_size -1 :
        
        t1 = 0
        t2 = k + 1
        d1 = - 1
        d2 = - k -2
    elif k > d_out - k_size -1 :
        
        t1 = k_size - (d_out - k)
        t2 = k_size
        d1 = - k +2
        d2 = 0
   
 
    res[:, k, :] = np.sum(
        np.flip(params, axis=1)[ np.newaxis, t1:t2, :,  :]
        * delta[  :, d2:d1, np.newaxis, :],
        axis=(1,3)
    )
    
print(res)

[[[ 0.00433082 -0.05166243]
  [-0.00276493 -0.02697257]
  [ 0.0026422  -0.03056124]
  [-0.00370273 -0.01470966]
  [-0.02291993 -0.00985766]
  [-0.01614343 -0.06263829]]

 [[ 0.00746722 -0.09136239]
  [-0.00652645 -0.04770518]
  [-0.01713646 -0.04693829]
  [-0.00247323 -0.08299252]
  [ 0.00967036 -0.07716034]
  [-0.01154363 -0.02805151]]

 [[-0.01919879 -0.03972489]
  [ 0.0108148  -0.08987615]
  [-0.01693522 -0.03171248]
  [ 0.00222175 -0.07348259]
  [-0.01957088 -0.04099506]
  [ 0.00695157 -0.09048239]]

 [[-0.02351044 -0.02649512]
  [ 0.00738936 -0.08977149]
  [ 0.00325793 -0.05163303]
  [ 0.00668545 -0.03558693]
  [-0.00800815 -0.00529647]
  [-0.01292963 -0.01969919]]] 3
[[[-0.01750764]
  [-0.00998772]
  [-0.03303721]
  [-0.02414664]
  [-0.02461112]
  [-0.02461112]
  [-0.02891653]
  [-0.01491328]]

 [[-0.00976391]
  [-0.03930859]
  [-0.0626876 ]
  [-0.06064831]
  [-0.06052671]
  [-0.06052671]
  [-0.0526105 ]
  [-0.02654301]]

 [[-0.01179393]
  [-0.02698904]
  [-0.06915165]
  [-0.0471